# Name : Rehman Kabir
# Roll # :PIAIC101302
# Assginment : implentation of any 50 numpy methods or attribute codes in jupyter notebook

In [3]:
import numpy as np

In [5]:
a = np.array([[1,2,3],[4,5,6]]) #array function which creates 2D array.
print(a)

[[1 2 3]
 [4 5 6]]


In [7]:
a.shape # shape function which gives the dimension of array.

(2, 3)

In [11]:
a.dtype # by default numpy datatype of array is int32. 

dtype('int32')

In [13]:
new_array=np.arange(6) # create 6 items in 1D array
print(new_array)

[0 1 2 3 4 5]


In [15]:
empty_array = np.empty(2) # Create an empty array with 2 elements  
empty_array

array([1.78538941e-046, 7.40914712e+123])

In [17]:
ones_array=np.ones(2) # create 1D array with element which will be 1.
ones_array

array([1., 1.])

In [20]:
linespaced_array = np.linspace(0, 10, num=5) #create an array with values that are spaced linearly in a specified interval
linespaced_array

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
demo_array = [5,2,1,6,2] 
np.sort(demo_array) #sort function can sort array elements in ascending order.

array([1, 2, 2, 5, 6])

In [25]:
a = np.array([1, 2, 3])
b = np.array([4,5,6])
np.concatenate((a, b)) #concatenation of two arrays

array([1, 2, 3, 4, 5, 6])

In [27]:
array_example = np.array([[[0, 1, 2, 3],[4, 5, 6, 7]],[[0, 1, 2, 3],[4, 5, 6, 7]], [[0 ,1 ,2, 3],[4, 5, 6, 7]]])
array_example.ndim #give the demensions of array.

3

In [34]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(3, 2) # reshape the array or matrix in row and column.
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [36]:
np.zeros(5) # create zeros elements in ndarray.

array([0., 0., 0., 0., 0.])

In [38]:
a2 = a[np.newaxis, :] # creating newaxis function to create dimension.
a2.shape

(1, 6)

In [40]:
a.sum() #sum the array elements.

21

In [44]:
a.min() #find minimum element of array


1

In [49]:
a.max() #find maximum element of array

6

In [48]:
a_unique = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a_unique) # get the unique values from array.
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [51]:
a = np.array([[1,2,3],[4,5,6]])
a.transpose() #get the transpose of matrix or array with convert rows into column and column into rows.

array([[1, 4],
       [2, 5],
       [3, 6]])

In [53]:
reversed_array = np.flip(a) #reverse arrays
reversed_array

array([[6, 5, 4],
       [3, 2, 1]])

In [54]:
a.flatten() #flat the array means convert nD array into 1D array.

array([1, 2, 3, 4, 5, 6])

In [57]:
a[1]= 0
a.ravel() # change the values in the parent array.

array([1, 2, 3, 0, 0, 0])

In [60]:
arr = np.array([1,2,3,4,5,6])
np.save('assignment1.npy',arr) # save array in numpy file 


In [62]:
np.load('assignment1.npy') # read array from numpy file.

array([1, 2, 3, 4, 5, 6])

In [66]:
np.power(100, 8, dtype=np.int64) #100 *10 * 8 as the datatype is int64

10000000000000000

In [68]:
np.indices((3,3)) #create a set of arrays (stacked as a one-higher dimensioned array),

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [70]:
a.size #total elements of array.

6

In [73]:
arr.itemsize 

4

In [76]:
c = arr.view() # array veiw
c

array([1, 2, 3, 4, 5, 6])

In [78]:
a = np.floor(10*np.random.random((3,4))) #generating 10 random number.
a

array([[4., 4., 3., 1.],
       [1., 3., 5., 0.],
       [1., 5., 9., 6.]])

In [80]:
a.resize((2,6)) # resize array row and column.
a

array([[4., 4., 3., 1., 1., 3.],
       [5., 0., 1., 5., 9., 6.]])

In [82]:
a = np.array([4.,2.])
b = np.array([3.,8.])
np.column_stack((a,b)) # returns a 2D array

array([[4., 3.],
       [2., 8.]])

In [84]:
np.hstack((a,b))           # the result is different

array([4., 2., 3., 8.])

In [86]:
x = np.arange(8.0) # split array into subarray
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [89]:
a = np.matrix('1 2; 3 4') #Create matrix
print(a)

[[1 2]
 [3 4]]


In [91]:
type(a) # show type of numpy (matrix, array, list...etc)

numpy.matrix

In [93]:
np.exp(arr) #exponential of array.

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 , 403.42879349])

In [95]:
np.sqrt(arr) #square of array.

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [97]:
a = np.full((2,2),7) #create a constant matrix
a

array([[7, 7],
       [7, 7]])

In [101]:
a=np.eye(2) # identity matrix
a

array([[1., 0.],
       [0., 1.]])

In [103]:
np.random.random((2,2)) # create a 2 X 2 matrix with random number

array([[0.85119426, 0.16543944],
       [0.1984044 , 0.55952622]])

In [105]:
len(a) # lenght of array

2

In [114]:
a = np.arange(6).reshape(3,2)
np.cos(a)



array([[ 1.        ,  0.54030231],
       [-0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219]])

In [112]:
np.sin(a)

array([[ 0.        ,  0.84147098],
       [ 0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427]])

In [115]:
np.log(a)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        ],
       [0.69314718, 1.09861229],
       [1.38629436, 1.60943791]])

In [117]:
np.mean(a)

2.5

In [120]:
np.median(a)

2.5

In [122]:
np.std(a)

1.707825127659933

In [124]:
np.copy(a)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [126]:
np.insert(a,2,1)

array([0, 1, 1, 2, 3, 4, 5])

In [127]:
np.delete(a,[1])

array([0, 2, 3, 4, 5])